# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DeltaWave
email: pkane2001@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  DeltaWave Audio file Null Tester and Comparison utility
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deltaw.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  pkane2001
company_name: Paul K.
google_analytics: UA-90967706-2
disqus_shortname: "deltawave.disqus.com"
disqus_id: "deltawave"

# Build settings
markdown: kramdown

remote-theme: documentation-theme-jekyll

output: web
topnav_title: DeltaWave Audio Null Comparator
site_title: DeltaWave documentation
feedback_disable: true

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sidebars:
- mydoc_sidebar

-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
    comments: true
    search: true
    sidebar: mydoc_sidebar
    topnav: topnav
